---
kind: pipeline
type: docker
name: stable

trigger:
  event:
    - push
    - tag

steps:
  - name: docker build (stable)
    when:
      event:
        include: [push]
      branch:
        include:
          - master
          - stable/*
          - stable-full/*
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKERHUB_USER
      password:
        from_secret: DOCKERHUB_PASS
      repo:
        from_secret: DOCKERHUB_REPOSITORY
      tags:
        - stable

  - name: docker build (stable tag)
    when:
      event:
        include: [tag]
      ref:
        include:
          - refs/tags/v*
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKERHUB_USER
      password:
        from_secret: DOCKERHUB_PASS
      repo:
        from_secret: DOCKERHUB_REPOSITORY
      tags:
        - stable
        - ${DRONE_TAG}

---
kind: pipeline
type: docker
name: stable-lite

trigger:
  event:
    - push
    - tag

steps:
  - name: setup lite
    when:
      event:
        include: [push, tag]
      branch:
        include:
          - master
          - stable/*
          - stable-lite/*
      ref:
        include:
          - refs/tags/v*
    image: plugins/docker
    commands:
      - ./make_lite.sh

  - name: docker build (lite)
    when:
      event:
        include: [push]
      branch:
        include:
          - master
          - stable/*
          - stable-lite/*
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKERHUB_USER
      password:
        from_secret: DOCKERHUB_PASS
      repo:
        from_secret: DOCKERHUB_REPOSITORY
      tags:
        - stable-lite

  - name: docker build (lite tag)
    when:
      event:
        include: [tag]
      ref:
        include:
          - refs/tags/v*
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKERHUB_USER
      password:
        from_secret: DOCKERHUB_PASS
      repo:
        from_secret: DOCKERHUB_REPOSITORY
      tags:
        - stable-lite
        - ${DRONE_TAG}-lite

---
kind: pipeline
type: docker
name: other-branches

trigger:
  event:
    - push
  branch:
    exclude:
      - master
      - feature/*
      - stable/*
      - stable-lite/*
      - docker_image_lite

steps:

  - name: docker build (feature)
    when:
      branch:
        include:
          - feature/*
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKERHUB_USER
      password:
        from_secret: DOCKERHUB_PASS
      repo:
        from_secret: DOCKERHUB_REPOSITORY
      tags:
        - edgerunner

  - name: docker build (testing)
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKERHUB_USER
      password:
       from_secret: DOCKERHUB_PASS
      repo:
        from_secret: DOCKERHUB_REPOSITORY
      tags:
        - testing

---
kind: pipeline
type: docker
name: test-image

trigger:
  event:
    - push
  branch:
    include:
      - only-for-testing

steps:

  - name: Test image
    image: docker:dind
    volumes:
    - name: dockersock
      path: /var/run
    commands:
    - sleep 5 # give docker enough time to start
    - ls ./testing/docker
    - /bin/sh ./testing/docker/setup_time.sh
    - /bin/sh ./testing/docker/setup_compose.sh
    - /bin/sh ./testing/docker/restore_db.sh
    - /bin/sh ./testing/docker/setup_videos.sh
    - /bin/sh ./testing/docker/run_tiktok_remover.sh
    - /bin/sh ./testing/docker/check_itr_output.sh
    - /bin/sh ./testing/docker/cleanup.sh

    # API Key: sHXdxnG2xoPNveGqJI8nZSlwTEMTFvILHqzCRFyfz4

services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run

volumes:
- name: dockersock
  temp: {}