kind: pipeline
name: default

steps:
- name: docker build (stable)
  when:
    branch:
      include:
      - master
      - stable/*
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKERHUB_USER
    password:
      from_secret: DOCKERHUB_PASS
    repo: alyssaholland99/immich-tiktok-remover
    tags:
    - stable

- name: setup lite
  when:
    branch:
      include:
      - stable-lite/*
      - docker_image_lite
  image: plugins/docker
  commands:
    - ./make_lite.sh

- name: docker build (lite)
  when:
    branch:
      include:
      - stable-lite/*
      - docker_image_lite
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKERHUB_USER
    password:
      from_secret: DOCKERHUB_PASS
    repo: alyssaholland99/immich-tiktok-remover
    tags:
    - stable-lite

- name: docker build (feature)
  when:
    branch:
      include:
      - feature/*
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKERHUB_USER
    password:
      from_secret: DOCKERHUB_PASS
    repo: alyssaholland99/immich-tiktok-remover
    tags:
    - edgerunner

- name: docker build (testing)
  when:
    branch:
      exclude:
      - master
      - feature/*
      - stable/*
      - stable-lite/*
      - docker_image_lite
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKERHUB_USER
    password:
      from_secret: DOCKERHUB_PASS
    repo: alyssaholland99/immich-tiktok-remover
    tags:
    - testing