---
kind: pipeline
type: docker
name: stable

trigger:
  event:
    - push
    - tag
  branch:
    - master
    - stable/*
    - stable-full/*
  ref:
    - refs/tags/v*

steps:
  - name: docker build (stable)
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKERHUB_USER
      password:
        from_secret: DOCKERHUB_PASS
      repo:
        from_secret: DOCKERHUB_REPOSITORY
      tags:
        - stable
        - ${DRONE_TAG}

---
kind: pipeline
type: docker
name: stable-lite

trigger:
  event:
    - push
    - tag
  branch:
    - master
    - stable/*
    - stable-lite/*
  ref:
    - refs/tags/v*

steps:
  - name: setup lite
    image: plugins/docker
    commands:
      - ./make_lite.sh

  - name: docker build (lite)
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKERHUB_USER
      password:
        from_secret: DOCKERHUB_PASS
      repo:
        from_secret: DOCKERHUB_REPOSITORY
      tags:
        - stable-lite
        - ${DRONE_TAG}

---
kind: pipeline
type: docker
name: other-branches

trigger:
  event:
    - push
  branch:
    exclude:
      - master
      - feature/*
      - stable/*
      - stable-lite/*
      - docker_image_lite

steps:
  - name: docker build (feature)
    when:
      branch:
        include:
          - feature/*
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKERHUB_USER
      password:
        from_secret: DOCKERHUB_PASS
      repo:
        from_secret: DOCKERHUB_REPOSITORY
      tags:
        - edgerunner

  - name: docker build (testing)
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKERHUB_USER
      password:
        from_secret: DOCKERHUB_PASS
      repo:
        from_secret: DOCKERHUB_REPOSITORY
      tags:
        - testing
