kind: pipeline
name: stable
type: docker

steps:
  - name: Build Stable Image
    when:
      any_of:
        - branch: { include: [ master, "stable/*", "stable-full/*" ] }
        - tag: { include: [ "v.*" ] }
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKERHUB_USER
      password:
        from_secret: DOCKERHUB_PASS
      repo:
        from_secret: DOCKERHUB_REPOSITORY
      tags:
        - stable

  - name: Setup Lite Environment
    when:
      any_of:
        - branch: { include: [ master, "stable/*", "stable-lite/*" ] }
        - tag: { include: [ "v.*" ] }
    commands:
      - ./make_lite.sh

  - name: Build Stable-Lite Image
    when:
      any_of:
        - branch: { include: [ master, "stable/*", "stable-lite/*" ] }
        - tag: { include: [ "v.*" ] }
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKERHUB_USER
      password:
        from_secret: DOCKERHUB_PASS
      repo:
        from_secret: DOCKERHUB_REPOSITORY
      tags:
        - stable-lite

kind: pipeline
name: other-branches
type: docker

steps:
  - name: Build Feature Branch Image
    when:
      branch:
        include:
          - feature/*
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKERHUB_USER
      password:
        from_secret: DOCKERHUB_PASS
      repo:
        from_secret: DOCKERHUB_REPOSITORY
      tags:
        - edgerunner

  - name: Build Testing Branch Image
    when:
      branch:
        exclude:
          - master
          - feature/*
          - stable/*
          - stable-lite/*
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKERHUB_USER
      password:
        from_secret: DOCKERHUB_PASS
      repo:
        from_secret: DOCKERHUB_REPOSITORY
      tags:
        - testing
