---
kind: pipeline
name: stable
type: docker

steps:

- name: docker build (stable)
  when:
    branch:
      include:
      - master
      - stable/*
      - stable-full/*
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKERHUB_USER
    password:
      from_secret: DOCKERHUB_PASS
    repo: DOCKERHUB_REPOSITORY
    tags:
    - stable

---
kind: pipeline
name: stable-lite
type: docker

steps:

- name: setup lite
  when:
    branch:
      include:
      - master
      - stable/*
      - stable-lite/*
  image: plugins/docker
  commands:
    - ./make_lite.sh

- name: docker build (lite)
  when:
    branch:
      include:
      - master
      - stable/*
      - stable-lite/*
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKERHUB_USER
    password:
      from_secret: DOCKERHUB_PASS
    repo: DOCKERHUB_REPOSITORY
    tags:
    - stable-lite

---
kind: pipeline
name: other-branches
type: docker

steps:

- name: docker build (feature)
  when:
    branch:
      include:
      - feature/*
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKERHUB_USER
    password:
      from_secret: DOCKERHUB_PASS
    repo: DOCKERHUB_REPOSITORY
    tags:
    - edgerunner

- name: docker build (testing)
  when:
    branch:
      exclude:
      - master
      - feature/*
      - stable/*
      - stable-lite/*
      - docker_image_lite
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKERHUB_USER
    password:
      from_secret: DOCKERHUB_PASS
    repo: DOCKERHUB_REPOSITORY
    tags:
    - testing

- name: Vunerability scan w/ Snyk
  depends_on:
    - docker build (testing)
    - docker build (feature)
  image: drone-plugins/drone-snyk
  pull: if-not-exists
  privileged: true
  settings:
      image: DOCKERHUB_REPOSITORY
      fail_on_issues: false