services:
  immich-tiktok-remover:
    container_name: immich-tiktok-remover
    image: alyssaholland99/immich-tiktok-remover:latest
    restart: unless-stopped
    environment:
      IMMICH_URL: "https://immich.yourserver.co.uk/"
      IMMICH_API: "your-immich-api-key"
      RESTART_TIMEOUT: 3600 # Time in seconds the script waits to restart (default 1hr)