services:
  immich-tiktok-remover:
    container_name: immich-tiktok-remover
    image: alyssaholland99/immich-tiktok-remover
    restart: unless-stopped
    environment:
      IMMICH_URL: "https://immich.yourserver.co.uk/"
      IMMICH_API: "your-immich-api-key"